# Generated by Django 2.2.6 on 2020-01-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200119_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishes',
        ),
        migrations.AddField(
            model_name='book',
            name='publishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Publish'),
        ),
    ]
