# Generated by Django 2.2.6 on 2020-01-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200119_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishes',
            new_name='redaction',
        ),
    ]
