# Generated by Django 2.2.6 on 2020-02-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200207_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='image',
        ),
    ]
