# Generated by Django 2.2.6 on 2020-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200207_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='20x20px', upload_to='image'),
        ),
    ]
